apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding-multiple
  namespace: default
subjects:
- kind: User
  name: user1  # Substitua pelo nome do primeiro usu치rio
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: user2  # Substitua pelo nome do segundo usu치rio
  apiGroup: rbac.authorization.k8s.io
# Adicione mais usu치rios conforme necess치rio
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
