apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
  namespace: default
subjects:
- kind: User
  name: <USERNAME>  # Substitua <USERNAME> pelo nome do usuário que deve ter acesso
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
